function varargout = WorkspaceGUI(varargin)
% WORKSPACEGUI M-file for WorkspaceGUI.fig generated using MATLAB's Guide
%__________________________________________________________________________
% USAGE: varargout = WorkspaceGUI(varargin)
%
% INPUT: none
%
% OUPUT: varargout = {'now','xx'},where xx is the hours, as a string
%        varargout = '', which is the selected time option
%__________________________________________________________________________

% 1 - INITIALIZATION CODE - DO NOT EDIT
    gui_Singleton = 1;
    gui_State = struct('gui_Name',       mfilename, ...
                       'gui_Singleton',  gui_Singleton, ...
                       'gui_OpeningFcn', @WorkspaceGUI_OpeningFcn, ...
                       'gui_OutputFcn',  @WorkspaceGUI_OutputFcn, ...
                       'gui_LayoutFcn',  [] , ...
                       'gui_Callback',   []);
    if nargin && ischar(varargin{1})
        gui_State.gui_Callback = str2func(varargin{1});
    end

    if nargout
        [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
    else
        gui_mainfcn(gui_State, varargin{:});
    end
    
% 2 - EXECUTES JUST BEFORE WORKSPACEGUI IS MADE VISIBLE.
    function WorkspaceGUI_OpeningFcn(hObject,eventdata,handles,varargin)
        set(handles.figure1,'Name','Date option');
        uiwait(handles.figure1);

% 3 - OUTPUTS FROM THIS FUNCTION ARE RETURNED TO THE COMMAND LINE.
    function varargout = WorkspaceGUI_OutputFcn(hObject,eventdata,handles) 
        varargout{1} = handles.output;
        close(handles.figure1);
 
% 4 - CALLBACKS FOR UICONTROLS AND FIGURE
    % 4.1 - Executes when "Use dates as selected" is pressed
        function selected_Callback(hObject, eventdata, handles)
            handles.output = '';
            guidata(hObject,handles);
            uiresume;

    % 4.2 - Executes when "Use actual date and time" is pressed
        function actual_Callback(hObject, eventdata, handles)
            hrs = get(handles.hours,'String');
            handles.output = {'now',hrs};
            guidata(hObject,handles);        
            uiresume;

    % 4.3 - Callbacks for hours edit box, this is generated by MATLAB: Do not
    % remove or function will not operate correctly
        function hours_Callback(hObject, eventdata, handles)
        function hours_CreateFcn(hObject, eventdata, handles)
        if ispc && isequal(get(hObject,'BackgroundColor'),...
                get(0,'defaultUicontrolBackgroundColor'))
            set(hObject,'BackgroundColor','white');
        end